In [8]:
#Panel Data System (Pandas)
#The Python Library must be installed

import pandas

dir(pandas)

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__deprecated_num_index_names',
 '__dir__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_testing',
 '_typing',
 '_version',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'json_normalize',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_orc',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_spss',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'read_xml',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [6]:
m = {
    "cars": ['ford', 'mazda','toyota'],
    'model':[2023, 2020, 2021]
}

nakel= pandas.DataFrame(m)
print(m)

{'cars': ['ford', 'mazda', 'toyota'], 'model': [2023, 2020, 2021]}

In [9]:
#Alias as

import pandas as pd

In [17]:
m = {
    "cars": ['ford', 'mazda','toyota'],
    'model':[2023, 2020, 2021]
}

nakel= pd.DataFrame(m)
print(nakel)

     cars  model
0    ford   2023
1   mazda   2020
2  toyota   2021

In [19]:
import pandas as pd

cars = ['ford', 'mazda','toyota']
halimah= pd.Series(cars)
print(halimah)

0      ford
1     mazda
2    toyota
dtype: object

In [20]:
#DataFrame
import pandas as pd

m = {
    "cars": ['ford', 'mazda','toyota'],
    'model':[2023, 2020, 2021],
    'num': [1,3,5]
}

df = pd.DataFrame(m)
print(df)

     cars  model  num
0    ford   2023    1
1   mazda   2020    3
2  toyota   2021    5

In [24]:
#Read from file
import pandas as pd

oye= pd.read_csv(r'C:\Users\TheMs\Documents\Data Analysis\Attrition dataseeet.csv')

oye

,Attrition,Business Travel,CF_age band,Department,Education Field,emp no,Gender,Job Role,Marital Status,Over Time,...,Standard Hours,Stock Option Level,Total Working Years,Work Life Balance,Years At Company,Years In Current Role,Years Since Last Promotion,Years With Curr Manager,Employee Status,Distance(Group)
0,Yes,Travel_Rarely,35 - 44,Sales,Life Sciences,STAFF-1,Female,Sales Executive,Single,Yes,...,80,0,8,1,6,4,0,5,Ex-Employees,Near
1,No,Travel_Frequently,45 - 54,R&D,Life Sciences,STAFF-2,Male,Research Scientist,Married,No,...,80,1,10,3,10,7,1,7,Current-Employees,Near
2,Yes,Travel_Rarely,35 - 44,R&D,Other,STAFF-3,Male,Laboratory Technician,Single,Yes,...,80,0,7,3,0,0,0,0,Ex-Employees,Near
3,Yes,Travel_Frequently,25 - 34,R&D,Life Sciences,STAFF-4,Female,Research Scientist,Married,Yes,...,80,0,8,3,8,7,3,0,Ex-Employees,Near
4,Yes,Travel_Rarely,25 - 34,R&D,Medical,STAFF-5,Male,Laboratory Technician,Married,No,...,80,1,6,3,2,2,2,2,Ex-Employees,Near
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2920,Yes,Travel_Frequently,35 - 44,Sales,Other,STAFF-2921,Male,Sales Executive,Single,Yes,...,80,0,13,4,11,9,6,7,Ex-Employees,Far
2921,Yes,Travel_Rarely,18-25,R&D,Life Sciences,STAFF-2922,Male,Research Scientist,Single,Yes,...,80,0,1,3,1,0,0,0,Ex-Employees,Near
2922,Yes,Travel_Rarely,18-25,Sales,Life Sciences,STAFF-2923,Male,Sales Representative,Divorced,Yes,...,80,1,3,3,3,2,0,2,Ex-Employees,Near
2923,Yes,Travel_Rarely,Under 26,Sales,Life Sciences,STAFF-2924,Male,Sales Representative,Divorced,Yes,...,80,1,3,3,3,2,0,2,Ex-Employees,Near
2924,Yes,Travel_Rarely,Under 27,Sales,Life Sciences,STAFF-2925,Male,Sales Representative,Divorced,Yes,...,80,1,3,3,3,2,0,2,Ex-Employees,Near

In [27]:
pd.options.display.max_rows =2925

df = pd.read_csv(r'C:\Users\TheMs\Documents\Data Analysis\Attrition dataseeet.csv')
df

     Attrition    Business Travel CF_age band Department   Education Field  \
0          Yes      Travel_Rarely     35 - 44      Sales     Life Sciences
1           No  Travel_Frequently     45 - 54        R&D     Life Sciences
2          Yes      Travel_Rarely     35 - 44        R&D             Other
3          Yes  Travel_Frequently     25 - 34        R&D     Life Sciences
4          Yes      Travel_Rarely     25 - 34        R&D           Medical
5          Yes  Travel_Frequently     25 - 34        R&D     Life Sciences
6          Yes      Travel_Rarely     55 plus        R&D           Medical
7          Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
8          Yes  Travel_Frequently     35 - 44        R&D     Life Sciences
9          Yes      Travel_Rarely     35 - 44        R&D           Medical
10         Yes      Travel_Rarely     35 - 44        R&D           Medical
11         Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
12         Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
13         Yes      Travel_Rarely     25 - 34        R&D           Medical
14         Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
15         Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
16         Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
17         Yes         Non_Travel       18-25        R&D           Medical
18         Yes      Travel_Rarely     45 - 54      Sales     Life Sciences
19         Yes      Travel_Rarely     35 - 44        R&D     Life Sciences
20         Yes         Non_Travel       18-25        R&D             Other
21         Yes      Travel_Rarely     35 - 44      Sales     Life Sciences
22         Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
23         Yes      Travel_Rarely       18-25        R&D     Life Sciences
24         Yes      Travel_Rarely     25 - 34        R&D           Medical
25          No      Travel_Rarely     45 - 54        R&D             Other
26         Yes  Travel_Frequently     25 - 34        R&D     Life Sciences
27          No      Travel_Rarely     35 - 44      Sales         Marketing
28          No      Travel_Rarely     35 - 44        R&D           Medical
29          No      Travel_Rarely     45 - 54      Sales         Marketing
30          No      Travel_Rarely     25 - 34        R&D           Medical
31          No      Travel_Rarely     35 - 44        R&D             Other
32          No      Travel_Rarely     25 - 34        R&D           Medical
33         Yes      Travel_Rarely     35 - 44      Sales  Technical Degree
34         Yes      Travel_Rarely       18-25        R&D           Medical
35          No      Travel_Rarely     35 - 44        R&D           Medical
36         Yes      Travel_Rarely     45 - 54      Sales         Marketing
37          No      Travel_Rarely     35 - 44      Sales         Marketing
38          No      Travel_Rarely     35 - 44        R&D     Life Sciences
39          No  Travel_Frequently     25 - 34      Sales     Life Sciences
40          No      Travel_Rarely     35 - 44        R&D             Other
41          No      Travel_Rarely     25 - 34        R&D     Life Sciences
42         Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
43          No  Travel_Frequently     25 - 34      Sales     Life Sciences
44          No  Travel_Frequently     25 - 34        R&D           Medical
45         Yes      Travel_Rarely     35 - 44        R&D  Technical Degree
46          No         Non_Travel     25 - 34      Sales         Marketing
47          No      Travel_Rarely     35 - 44        R&D     Life Sciences
48          No  Travel_Frequently     45 - 54      Sales         Marketing
49          No      Travel_Rarely     35 - 44        R&D     Life Sciences
50         Yes      Travel_Rarely     45 - 54        R&D     Life Sciences
51         Yes      Travel_Rarely     25 - 34        R&D  Technical Degree
52          No      Travel_Rarely     35 - 44      Sales         Marketing
53          No         Non_Travel     35 - 44        R&D           Medical
54          No      Travel_Rarely     25 - 34      Sales         Marketing
55          No  Travel_Frequently     25 - 34        R&D     Life Sciences
56          No  Travel_Frequently     35 - 44      Sales     Life Sciences
57          No      Travel_Rarely     35 - 44        R&D           Medical
58          No      Travel_Rarely     25 - 34        R&D     Life Sciences
59          No      Travel_Rarely     35 - 44        R&D     Life Sciences
60          No      Travel_Rarely     25 - 34        R&D           Medical
61          No  Travel_Frequently     35 - 44        R&D     Life Sciences
62          No      Travel_Rarely     45 - 54        R&D           Medical
63          No      Travel_Rarely     55 plus      Sales     Life Sciences
64          No      Travel_Rarely     35 - 44        R&D  Technical Degree
65          No      Travel_Rarely     55 plus        R&D           Medical
66          No  Travel_Frequently     35 - 44        R&D     Life Sciences
67          No      Travel_Rarely     45 - 54        R&D     Life Sciences
68          No  Travel_Frequently     35 - 44        R&D           Medical
69         Yes      Travel_Rarely     35 - 44        R&D           Medical
70          No  Travel_Frequently     55 plus      Sales     Life Sciences
71          No      Travel_Rarely     25 - 34        R&D     Life Sciences
72          No      Travel_Rarely     25 - 34        R&D           Medical
73          No      Travel_Rarely     25 - 34        R&D     Life Sciences
74          No      Travel_Rarely     35 - 44        R&D     Life Sciences
75          No      Travel_Rarely     25 - 34        R&D     Life Sciences
76          No      Travel_Rarely     35 - 44      Sales         Marketing
77          No      Travel_Rarely     45 - 54        R&D             Other
78          No      Travel_Rarely     35 - 44        R&D           Medical
79          No      Travel_Rarely     45 - 54         HR           Medical
80          No      Travel_Rarely     25 - 34        R&D     Life Sciences
81          No      Travel_Rarely     35 - 44        R&D           Medical
82          No      Travel_Rarely     55 plus      Sales     Life Sciences
83          No         Non_Travel     35 - 44        R&D           Medical
84          No      Travel_Rarely     25 - 34        R&D           Medical
85          No      Travel_Rarely     55 plus        R&D     Life Sciences
86          No      Travel_Rarely       18-25      Sales  Technical Degree
87          No      Travel_Rarely     45 - 54        R&D     Life Sciences
88          No      Travel_Rarely     25 - 34        R&D     Life Sciences
89         Yes      Travel_Rarely     45 - 54      Sales           Medical
90          No  Travel_Frequently     35 - 44        R&D     Life Sciences
91          No      Travel_Rarely     45 - 54      Sales         Marketing
92          No      Travel_Rarely     25 - 34      Sales           Medical
93          No  Travel_Frequently     45 - 54        R&D           Medical
94          No      Travel_Rarely     25 - 34      Sales           Medical
95          No      Travel_Rarely     45 - 54        R&D  Technical Degree
96          No      Travel_Rarely       18-25      Sales             Other
97          No         Non_Travel     25 - 34      Sales           Medical
98          No      Travel_Rarely     55 plus      Sales           Medical
99          No         Non_Travel     35 - 44        R&D           Medical
100        Yes      Travel_Rarely     35 - 44         HR   Human Resources
101         No      Travel_Rarely     25 - 34        R&D     Life Sciences
102        Yes  Travel_Frequently       18-25        R&D     Life Sciences
103         No      Travel_Rarely     25 - 34        R&D             Other
104         No         Non_Travel     35 - 44        R&D     Life Sciences
105         No         Non_Travel     55 plus         HR   Human Resources
106         No  Travel_Frequently     45 - 54        R&D     Life Sciences
107        Yes      Travel_Rarely     25 - 34      Sales         Marketing
108         No      Travel_Rarely     25 - 34        R&D           Medical
109         No      Travel_Rarely       18-25        R&D           Medical
110         No  Travel_Frequently     45 - 54        R&D           Medical
111        Yes  Travel_Frequently     25 - 34        R&D     Life Sciences
112         No         Non_Travel     45 - 54         HR   Human Resources
113         No      Travel_Rarely       18-25        R&D     Life Sciences
114         No      Travel_Rarely     25 - 34        R&D     Life Sciences
115         No      Travel_Rarely     35 - 44      Sales     Life Sciences
116         No      Travel_Rarely     25 - 34        R&D           Medical
117         No  Travel_Frequently     35 - 44      Sales  Technical Degree
118         No      Travel_Rarely     35 - 44        R&D     Life Sciences
119         No  Travel_Frequently     35 - 44      Sales     Life Sciences
120         No  Travel_Frequently     25 - 34        R&D     Life Sciences
121         No         Non_Travel     25 - 34      Sales         Marketing
122        Yes      Travel_Rarely     55 plus        R&D     Life Sciences
123         No      Travel_Rarely     45 - 54        R&D     Life Sciences
124        Yes      Travel_Rarely     25 - 34      Sales     Life Sciences
125         No      Travel_Rarely     25 - 34        R&D             Other
126        Yes      Travel_Rarely     55 plus        R&D           Medical
127        Yes      Travel_Rarely       18-25      Sales         Marketing
128         No      Travel_Rarely       18-25        R&D  Technical Degree
129         No      Travel_Rarely     45 - 54        R&D           Medical
130         No  Travel_Frequently     35 - 44        R&D           Medical
131         No  Travel_Frequently     45 - 54      Sales         Marketing
132        Yes      Travel_Rarely     25 - 34      Sales     Life Sciences
133         No      Travel_Rarely     35 - 44      Sales     Life Sciences
134         No      Travel_Rarely     25 - 34         HR     Life Sciences
135         No      Travel_Rarely     35 - 44        R&D           Medical
136        Yes  Travel_Frequently     45 - 54        R&D     Life Sciences
137         No      Travel_Rarely     35 - 44      Sales     Life Sciences
138         No      Travel_Rarely     25 - 34      Sales     Life Sciences
139         No      Travel_Rarely     25 - 34         HR   Human Resources
140        Yes      Travel_Rarely     25 - 34        R&D           Medical
141         No      Travel_Rarely     45 - 54        R&D           Medical
142         No      Travel_Rarely     35 - 44        R&D  Technical Degree
143         No      Travel_Rarely     25 - 34        R&D     Life Sciences
144         No  Travel_Frequently     25 - 34      Sales           Medical
145         No      Travel_Rarely     25 - 34        R&D  Technical Degree
146         No      Travel_Rarely     25 - 34        R&D           Medical
147         No  Travel_Frequently     35 - 44        R&D     Life Sciences
148         No      Travel_Rarely     35 - 44        R&D     Life Sciences
149         No      Travel_Rarely       18-25        R&D           Medical
150         No  Travel_Frequently     35 - 44        R&D           Medical
151         No      Travel_Rarely     35 - 44      Sales         Marketing
152         No      Travel_Rarely     45 - 54      Sales         Marketing
153         No      Travel_Rarely     45 - 54        R&D     Life Sciences
154         No  Travel_Frequently     25 - 34      Sales         Marketing
155         No         Non_Travel     25 - 34        R&D  Technical Degree
156         No      Travel_Rarely     45 - 54        R&D           Medical
157         No      Travel_Rarely     55 plus        R&D           Medical
158         No      Travel_Rarely     35 - 44      Sales         Marketing
159         No  Travel_Frequently     25 - 34      Sales         Marketing
160         No      Travel_Rarely       18-25        R&D           Medical
161         No         Non_Travel     25 - 34        R&D           Medical
162         No      Travel_Rarely     25 - 34        R&D           Medical
163         No      Travel_Rarely     55 plus        R&D     Life Sciences
164         No         Non_Travel     25 - 34        R&D           Medical
165         No      Travel_Rarely     45 - 54        R&D     Life Sciences
166         No      Travel_Rarely     35 - 44        R&D     Life Sciences
167         No      Travel_Rarely     25 - 34      Sales     Life Sciences
168         No      Travel_Rarely     35 - 44      Sales     Life Sciences
169         No      Travel_Rarely     25 - 34        R&D     Life Sciences
170         No      Travel_Rarely     25 - 34        R&D  Technical Degree
171        Yes  Travel_Frequently       18-25      Sales  Technical Degree
172         No  Travel_Frequently     35 - 44        R&D           Medical
173         No         Non_Travel     25 - 34        R&D           Medical
174         No      Travel_Rarely     45 - 54      Sales     Life Sciences
175         No      Travel_Rarely     55 plus        R&D     Life Sciences
176         No      Travel_Rarely     25 - 34        R&D     Life Sciences
177        Yes      Travel_Rarely       18-25        R&D     Life Sciences
178         No      Travel_Rarely     45 - 54      Sales         Marketing
179         No      Travel_Rarely     35 - 44        R&D     Life Sciences
180         No      Travel_Rarely     25 - 34        R&D           Medical
181         No      Travel_Rarely     25 - 34        R&D           Medical
182        Yes      Travel_Rarely     35 - 44      Sales         Marketing
183         No      Travel_Rarely     45 - 54        R&D           Medical
184         No      Travel_Rarely     45 - 54        R&D           Medical
185         No      Travel_Rarely     25 - 34        R&D           Medical
186         No      Travel_Rarely     35 - 44        R&D           Medical
187         No      Travel_Rarely     55 plus        R&D           Medical
188         No  Travel_Frequently     25 - 34        R&D     Life Sciences
189         No      Travel_Rarely     45 - 54        R&D           Medical
190         No      Travel_Rarely     45 - 54        R&D     Life Sciences
191         No      Travel_Rarely     25 - 34        R&D           Medical
192        Yes      Travel_Rarely     35 - 44        R&D     Life Sciences
193         No         Non_Travel     35 - 44        R&D           Medical
194         No         Non_Travel     45 - 54        R&D           Medical
195         No      Travel_Rarely     35 - 44        R&D     Life Sciences
196         No  Travel_Frequently     35 - 44        R&D           Medical
197         No         Non_Travel     35 - 44        R&D           Medical
198         No      Travel_Rarely     35 - 44        R&D     Life Sciences
199         No      Travel_Rarely     35 - 44        R&D  Technical Degree
200         No  Travel_Frequently     25 - 34        R&D  Technical Degree
201         No         Non_Travel     45 - 54        R&D     Life Sciences
202         No  Travel_Frequently     25 - 34        R&D           Medical
203         No      Travel_Rarely     35 - 44        R&D           Medical
204        Yes      Travel_Rarely     35 - 44        R&D           Medical
205        Yes      Travel_Rarely     25 - 34      Sales         Marketing
206         No      Travel_Rarely       18-25        R&D     Life Sciences
207         No  Travel_Frequently     35 - 44        R&D           Medical
208         No         Non_Travel     35 - 44        R&D     Life Sciences
209         No      Travel_Rarely     45 - 54        R&D           Medical
210        Yes      Travel_Rarely     25 - 34      Sales           Medical
211         No         Non_Travel     25 - 34        R&D     Life Sciences
212         No  Travel_Frequently     25 - 34      Sales     Life Sciences
213         No      Travel_Rarely     45 - 54        R&D     Life Sciences
214        Yes      Travel_Rarely     25 - 34        R&D  Technical Degree
215         No      Travel_Rarely     35 - 44      Sales     Life Sciences
216        Yes  Travel_Frequently     25 - 34      Sales         Marketing
217        Yes      Travel_Rarely     25 - 34        R&D  Technical Degree
218         No         Non_Travel     45 - 54      Sales           Medical
219         No      Travel_Rarely     45 - 54      Sales         Marketing
220         No      Travel_Rarely     35 - 44        R&D     Life Sciences
221         No      Travel_Rarely     25 - 34        R&D           Medical
222         No  Travel_Frequently     35 - 44        R&D             Other
223         No      Travel_Rarely     35 - 44      Sales     Life Sciences
224         No         Non_Travel     25 - 34        R&D           Medical
225         No      Travel_Rarely     55 plus        R&D     Life Sciences
226         No  Travel_Frequently     35 - 44      Sales         Marketing
227         No  Travel_Frequently     25 - 34      Sales           Medical
228         No  Travel_Frequently     35 - 44      Sales         Marketing
229        Yes      Travel_Rarely     25 - 34        R&D           Medical
230         No      Travel_Rarely     45 - 54        R&D     Life Sciences
231         No      Travel_Rarely     35 - 44        R&D  Technical Degree
232         No      Travel_Rarely     55 plus         HR           Medical
233         No      Travel_Rarely     45 - 54      Sales           Medical
234        Yes      Travel_Rarely     25 - 34        R&D           Medical
235         No      Travel_Rarely     35 - 44      Sales         Marketing
236        Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
237         No         Non_Travel     45 - 54      Sales     Life Sciences
238         No      Travel_Rarely     25 - 34      Sales     Life Sciences
239        Yes      Travel_Rarely     25 - 34        R&D     Life Sciences
240         No      Travel_Rarely     35 - 44        R&D           Medical
241         No         Non_Travel     25 - 34      Sales         Marketing
242         No      Travel_Rarely     35 - 44        R&D     Life Sciences
243         No      Travel_Rarely     35 - 44        R&D  Technical Degree
244         No      Travel_Rarely     45 - 54        R&D             Other
245         No  Travel_Frequently     25 - 34        R&D           Medical
246         No      Travel_Rarely     25 - 34        R&D     Life Sciences
247         No      Travel_Rarely     25 - 34        R&D     Life Sciences
248         No      Travel_Rarely     35 - 44        R&D           Medical
249         No  Travel_Frequently     45 - 54        R&D     Life Sciences
250        Yes  Travel_Frequently     35 - 44        R&D           Medical
251         No  Travel_Frequently     35 - 44        R&D  Technical Degree
252         No      Travel_Rarely     25 - 34        R&D     Life Sciences
253         No      Travel_Rarely     35 - 44        R&D     Life Sciences
254         No      Travel_Rarely     25 - 34      Sales         Marketing
255         No      Travel_Rarely     25 - 34        R&D     Life Sciences
256         No      Travel_Rarely     35 - 44        R&D           Medical
257         No      Travel_Rarely     35 - 44        R&D           Medical
258         No      Travel_Rarely     45 - 54        R&D     Life Sciences
259        Yes  Travel_Frequently     25 - 34        R&D           Medical
260         No  Travel_Frequently     25 - 34        R&D     Life Sciences
261         No         Non_Travel     35 - 44      Sales     Life Sciences
262         No      Travel_Rarely     25 - 34        R&D  Technical Degree
263         No      Travel_Rarely     45 - 54      Sales  Technical Degree
264        Yes      Travel_Rarely     25 - 34        R&D     Life Sciences